### ISSUE TITLE
[VS add-in] failed preview (missing solution?)

### ISSUE THREAD

**Issue by hades-incarnate** [UXDivers/Gorilla-Player-Support#260] opened 2017-10-29 12:55 UTC
I installed Gorilla player and VS add-in, localhos:9014 works. When I try to preview the XAML page I get an error in VS:

![image](https://user-images.githubusercontent.com/15175507/32143391-cdcd6894-bca8-11e7-9a96-c80684b51fcb.png)

None of the three logs seem to have any errors the only thing odd is that it keeps trying to find and then adds the solution every second:

```
{"level":"info","message":"Setting Target: Views\\LoginPage.xaml (C:\\project\\MyXamarinApp\\MyXamarinApp.App\\MyXamarinApp.App\\MyXamarinApp.App.csproj) requested from VS (15.0)","timestamp":"2017-10-29T12:01:29.271Z"}
{"level":"info","message":"Solution not found","timestamp":"2017-10-29T12:01:29.271Z"}
{"level":"info","message":"Adding solution (from VS - 15.0): C:\\project\\MyXamarinApp\\MyXamarinApp.sln ","timestamp":"2017-10-29T12:01:29.272Z"}
{"level":"info","message":"Setting Target: Views\\AboutPage.xaml (C:\\project\\MyXamarinApp\\MyXamarinApp.App\\MyXamarinApp.App\\MyXamarinApp.App.csproj) requested from VS (15.0)","timestamp":"2017-10-29T12:04:12.374Z"}
{"level":"info","message":"Solution not found","timestamp":"2017-10-29T12:04:12.374Z"}
{"level":"info","message":"Adding solution (from VS - 15.0): C:\\project\\MyXamarinApp\\MyXamarinApp.sln ","timestamp":"2017-10-29T12:04:12.375Z"}
{"level":"info","message":"Setting Target: Views\\AboutPage.xaml (C:\\project\\MyXamarinApp\\MyXamarinApp.App\\MyXamarinApp.App\\MyXamarinApp.App.csproj) requested from VS (15.0)","timestamp":"2017-10-29T12:04:13.392Z"}
{"level":"info","message":"Solution not found","timestamp":"2017-10-29T12:04:13.393Z"}
{"level":"info","message":"Adding solution (from VS - 15.0): C:\\project\\MyXamarinApp\\MyXamarinApp.sln ","timestamp":"2017-10-29T12:04:13.394Z"}
{"level":"info","message":"Setting Target: Views\\AboutPage.xaml (C:\\project\\MyXamarinApp\\MyXamarinApp.App\\MyXamarinApp.App\\MyXamarinApp.App.csproj) requested from VS (15.0)","timestamp":"2017-10-29T12:04:14.399Z"}
{"level":"info","message":"Solution not found","timestamp":"2017-10-29T12:04:14.399Z"}
{"level":"info","message":"Adding solution (from VS - 15.0): C:\\project\\MyXamarinApp\\MyXamarinApp.sln ","timestamp":"2017-10-29T12:04:14.401Z"}
{"level":"info","message":"Setting Target: Views\\AboutPage.xaml (C:\\project\\MyXamarinApp\\MyXamarinApp.App\\MyXamarinApp.App\\MyXamarinApp.App.csproj) requested from VS (15.0)","timestamp":"2017-10-29T12:04:15.415Z"}
{"level":"info","message":"Solution not found","timestamp":"2017-10-29T12:04:15.416Z"}
{"level":"info","message":"Adding solution (from VS - 15.0): C:\\project\\MyXamarinApp\\MyXamarinApp.sln ","timestamp":"2017-10-29T12:04:15.416Z"}
{"level":"info","message":"Setting Target: Views\\AboutPage.xaml (C:\\project\\MyXamarinApp\\MyXamarinApp.App\\MyXamarinApp.App\\MyXamarinApp.App.csproj) requested from VS (15.0)","timestamp":"2017-10-29T12:04:16.434Z"}
{"level":"info","message":"Solution not found","timestamp":"2017-10-29T12:04:16.434Z"}
{"level":"info","message":"Adding solution (from VS - 15.0): C:\\project\\MyXamarinApp\\MyXamarinApp.sln ","timestamp":"2017-10-29T12:04:16.435Z"}
{"level":"info","message":"Setting Target: Views\\AboutPage.xaml (C:\\project\\MyXamarinApp\\MyXamarinApp.App\\MyXamarinApp.App\\MyXamarinApp.App.csproj) requested from VS (15.0)","timestamp":"2017-10-29T12:04:17.441Z"}
{"level":"info","message":"Solution not found","timestamp":"2017-10-29T12:04:17.441Z"}
{"level":"info","message":"Adding solution (from VS - 15.0): C:\\project\\MyXamarinApp\\MyXamarinApp.sln ","timestamp":"2017-10-29T12:04:17.442Z"}
{"level":"info","message":"Setting Target: Views\\AboutPage.xaml (C:\\project\\MyXamarinApp\\MyXamarinApp.App\\MyXamarinApp.App\\MyXamarinApp.App.csproj) requested from VS (15.0)","timestamp":"2017-10-29T12:04:18.458Z"}
{"level":"info","message":"Solution not found","timestamp":"2017-10-29T12:04:18.458Z"}
{"level":"info","message":"Adding solution (from VS - 15.0): C:\\project\\MyXamarinApp\\MyXamarinApp.sln ","timestamp":"2017-10-29T12:04:18.459Z"}
{"level":"info","message":"Setting Target: Views\\AboutPage.xaml (C:\\project\\MyXamarinApp\\MyXamarinApp.App\\MyXamarinApp.App\\MyXamarinApp.App.csproj) requested from VS (15.0)","timestamp":"2017-10-29T12:04:19.465Z"}
{"level":"info","message":"Solution not found","timestamp":"2017-10-29T12:04:19.466Z"}
{"level":"info","message":"Adding solution (from VS - 15.0): C:\\project\\MyXamarinApp\\MyXamarinApp.sln ","timestamp":"2017-10-29T12:04:19.467Z"}
{"level":"info","message":"Setting Target: Views\\AboutPage.xaml (C:\\project\\MyXamarinApp\\MyXamarinApp.App\\MyXamarinApp.App\\MyXamarinApp.App.csproj) requested from VS (15.0)","timestamp":"2017-10-29T12:04:20.473Z"}
{"level":"info","message":"Solution not found","timestamp":"2017-10-29T12:04:20.473Z"}
{"level":"info","message":"Adding solution (from VS - 15.0): C:\\project\\MyXamarinApp\\MyXamarinApp.sln ","timestamp":"2017-10-29T12:04:20.475Z"}
{"level":"info","message":"Setting Target: Views\\AboutPage.xaml (C:\\project\\MyXamarinApp\\MyXamarinApp.App\\MyXamarinApp.App\\MyXamarinApp.App.csproj) requested from VS (15.0)","timestamp":"2017-10-29T12:04:21.486Z"}
{"level":"info","message":"Solution not found","timestamp":"2017-10-29T12:04:21.486Z"}
{"level":"info","message":"Adding solution (from VS - 15.0): C:\\project\\MyXamarinApp\\MyXamarinApp.sln ","timestamp":"2017-10-29T12:04:21.487Z"}
```

**Comment by LeoHere** [comment] 2017-10-30 09:12
@hades-incarnate can you please send me the complete logs to l r o d r i g u e z at uxdivers.com?

Before doing so, please 
- delete them
- restart Gorilla Desktop app (status bar icon-> Quit-> reopen) 
- set verbosity in debug
- try to preview the page again a couple of times

**Comment by Mr-Pearce** [comment] 2017-11-13 08:00
Looks like i have the same issue.
Do you need more logs?

**Comment by leemorris** [comment] 2017-11-30 11:07
I am seeing the same issue. Do yo need more logs?

**Comment by Mr-Pearce** [comment] 2017-12-12 13:10
is there any update on this error? Its two month old and Gorilla player is still not working

**Comment by LeoHere** [comment] 2017-12-21 19:00
@Mr-Pearce sorry for the delay. Unfortunately, we were not able to reproduce the issue so far. There is a new version of Gorilla with .NET Standard support (still beta testing it). If you want I can share the bits with you to test if the problem is fixed there. There were several changes in the way the solutions are loaded, so it might be.

If you want to test it write me to l r o d r i g u e z at uxdivers.com.

**Comment by Mr-Pearce** [comment] 2017-12-22 08:37
The new Version fixes this and works great

**Comment by LeoHere** [comment] 2017-12-22 09:54
@Mr-Pearce great! Thanks for let us know.

@hades-incarnate, @leemorris if you want to get it please please write me as I mentioned above.

**Comment by LeoHere** [comment] 2018-01-02 11:13
Hi, Gorilla 1.2 with .NET Standard support has been released. Base on what @Mr-Pearce  tested, this version also fixes the issue mentioned here. Please check [this blog post](https://grialkit.com/2017/12/gorilla-player-1-2-net-standard-support/) for more information. Closing the issue. If you find out the issue still persists after the update feel free to reopen it.

**Closed by LeoHere** 2018-01-02 11:13 UTC
