### ISSUE TITLE
Supporting UTF-8

### ISSUE THREAD

**Issue by reader-man** [UXDivers/Gorilla-Player-Support#82] opened 2016-05-03 20:22 UTC
Hi,
 I am using ur GORILLA PLAYER to show some buttons, in non-Latin languages, like Hebrew and Arabic, but it could not render them.

can you please look into it.

**Comment by LeoHere** [comment] 2016-05-05 09:32
Hi, thanks for your feedback. I can't reproduce this issue. Can you provide a sample solution to reproduce it?

**Comment by reader-man** [comment] 2016-05-05 09:57
I was using this:
                <Label Text="تجربة"  />
And it was not rendering correctly.
But strangely, it looks like its working correctly now.

Thanks.

**Comment by jpbrocca** [comment] 2016-05-09 21:25
hi @reader-man,

can we close this issue or are you still having issues?

thanks
JP

**Comment by reader-man** [comment] 2016-05-10 18:01
Sorry too many eMails these days.

Yes, close it please, its working 100%.

**Comment by reader-man** [comment] 2016-05-10 18:01
Thanks a lot.

**Comment by jpbrocca** [comment] 2016-05-10 19:21
No worries, it happens all the time ;)

Have a great day!
JP

**Closed by jpbrocca** 2016-05-10 19:21 UTC
