### ISSUE TITLE
Working with JsonData sample

### ISSUE THREAD

**Issue by cassionandi** [UXDivers/Gorilla-Player-Support#142] opened 2016-07-22 00:49 UTC
Hi!

I'm using v0.9.1.2 and trying to load sample data with JsonData.

Follows the XAML:
`    <ContentPage.Resources>
        <ResourceDictionary>
            <gorilla:JsonData x:Key="People">
                [
                    { "Name": "John", "Age":29},
                    { "Name": "Pam", "Age":32},
                    { "Name": "Casy", "Age":58 },
                    { "Name": "Susan", "Age":29}
                ]
            </gorilla:JsonData>
        </ResourceDictionary>
    </ContentPage.Resources>
`

<ContentPage.Content>

      <ListView ItemsSource="{Binding Source={StaticResource People}, Path=Obj}">
          <ListView.ItemTemplate>
              <DataTemplate>
                  <ViewCell>
                    <StackLayout>
                          <Label Text="{Binding Name}" VerticalOptions="Center" />
                          <Label Text="{Binding Age}" VerticalOptions="Center" />
                      </StackLayout>
                  </ViewCell>
              </DataTemplate>
          </ListView.ItemTemplate>
      </ListView>`

Code based on docs: http://docs.gorillaplayer.com/how-to/working-with-sample-data.html

Sad Gorilla keeps tell me: 
![1](https://cloud.githubusercontent.com/assets/699167/17043433/f4f2ad1a-4f8c-11e6-9eda-bf67db43b8e9.PNG)
details:
![2](https://cloud.githubusercontent.com/assets/699167/17043436/fc1020be-4f8c-11e6-9738-b0887ccfce5f.PNG)

Could someone help me with that? : )

**Comment by LeoHere** [comment] 2016-07-22 10:07
Can you paste the complete XAML of your page? I copy paste the XAML you posted and it is previewing as expected...may be the issue is elsewhere.

BTW, I would recommend you to use sample data using the ```SampleData.json``` approach. It is a cleaner approach. Still, for quick tests the ```JsonData``` is fine.

**Comment by cassionandi** [comment] 2016-07-22 11:22
Of course Leonardo! Thanks for your advice on SampleData.json. Will try it right now!

Here is the XAML for JsonData:
`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:AppName"
             xmlns:gorilla="clr-namespace:UXDivers.Gorilla;assembly=UXDivers.Gorilla.Common"
             x:Class="AppName.MainPage">
  <ContentPage.Resources>
    <ResourceDictionary>
      <gorilla:JsonData x:Key="People"> [ { "Name": "John", "Age":29}, { "Name": "Pam", "Age":32}, { "Name": "Casy", "Age":58 }, { "Name": "Susan", "Age":29} ] </gorilla:JsonData>
    </ResourceDictionary>
  </ContentPage.Resources>
  <ListView ItemsSource="{Binding Source={StaticResource People}, Path=Obj}">
    <ListView.ItemTemplate>
      <DataTemplate>
        <ViewCell>
          <StackLayout>
            <Label Text="{Binding Name}" VerticalOptions="Center" />
            <Label Text="{Binding Age}" VerticalOptions="Center" />
          </StackLayout>
        </ViewCell>
      </DataTemplate>
    </ListView.ItemTemplate>
  </ListView>
</ContentPage>`

The emulator is running API 19 for Android. This is the MainPage for the application, has no logic on code behind. VS is tell me that binding Name and Age "Cannot resolve properly 'Name' in data context of type 'object'

**Comment by LeoHere** [comment] 2016-07-22 12:11
I tried with the full XAML and still can't reproduce it :(
I tried it in API 19 emulator too, but using XS. Later (i'm in the middle of VS Update) I will try it in VS. 

In the meantime, please use ```SampleData.json``` and let me know if it works for you.

**Comment by cassionandi** [comment] 2016-07-22 12:18
Problem solved about JsonData, seems like I copied the code with a little garbage at the end.
![garbage](https://cloud.githubusercontent.com/assets/699167/17056861/c87707da-4fec-11e6-9686-e8d8fbea554f.PNG)

Removing the symbol solved this issue.

SampleData.json worked out of the box. Thank you for the support Leonardo.

**Comment by LeoHere** [comment] 2016-07-22 12:20
Good to know! Thanks. Closing the issue now.

**Closed by LeoHere** 2016-07-22 12:20 UTC
