### ISSUE TITLE
StaticResource not found 

### ISSUE THREAD

**Issue by MarcinDr** [UXDivers/Gorilla-Player-Support#163] opened 2016-09-15 06:56 UTC
As described in title, we have problem with static resources:

Our view code:

![screen shot 2016-09-15 at 08 55 24](https://cloud.githubusercontent.com/assets/13198380/18540910/2bd6b0ae-7b22-11e6-93cc-1c26bf4444b9.png)

SendReport style is defined in App.xaml ResourceDictionary. 

Here is what Gorilla Player shows:
![screen shot 2016-09-15 at 08 52 04](https://cloud.githubusercontent.com/assets/13198380/18540899/17e381c6-7b22-11e6-9cfa-bded505e9d2f.png)

If we change 'StaticResource' for 'DynamicResource' it works but honestly that not a final solution for us.

Cheers

**Comment by LeoHere** [comment] 2016-09-16 11:53
That is weird, it should work.

I can't reproduce it. 

I tried with:

~~~
<?xml version="1.0" encoding="UTF-8"?>
<view:BaseContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
			 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
			 xmlns:view="clr-namespace:SupportTests;assembly=SupportTests" 
			 x:Class="SupportTests.TestMarcinDr1">
	<StackLayout>
		<StackLayout>
			<Button Style="{StaticResource SendReport}" />
		</StackLayout>
	</StackLayout>
</view:BaseContentPage>
~~~

The ```App.xaml``` contains:

~~~
<?xml version="1.0" encoding="UTF-8"?>
<Application xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="SupportTests.App">
	<Application.Resources>
		<ResourceDictionary>
                        ...
			 <Style x:Key="SendReport" TargetType="Button">
				<Setter Property="BackgroundColor" Value="Lime"/>
				<Setter Property="TextColor" Value="Red"/>
			</Style>  
		</ResourceDictionary>
	</Application.Resources>
</Application>
~~~

Can you provide more details about your App.xaml?

Any chance I can get access to the code to test it? It would be much faster. If it is possible just write me to l r o d r i g u e z at u x d i v e r s . c o m

**Comment by MarcinDr** [comment] 2016-09-16 13:37
Sorry I'm not allowed to share whole code :)

What is weird if I define ResourceDictionary for this page and define SendReport button there then it complains about not recognizing Static Resource "ViewModelLocator" not about the SendReport resource.

**Comment by nexussays** [comment] 2016-10-13 09:25
I am having what appears to be the same problem. StaticResources cannot be found but if I change them all to DynamicResource it works. If there's not been any progress I can try simplifying the project down until the problem goes away or I have a minimal repro scenario.

**Comment by LeoHere** [comment] 2016-10-13 09:33
So far we were not able to reproduce the issue, so yes please, having that project would be very useful. Thanks!

**Comment by nexussays** [comment] 2016-10-13 09:47
Well that was quick. The error is consistently reproducible if the page in question inherits my base class (`<view:BasePage`) and it works if it's just `<ContentPage>` directly.

This is all BasePage.xaml is:

```xaml
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="presentation.view.BasePage"
             IsBusy="{Binding IsBusy}">
</ContentPage>
```
```cs
public partial class BasePage : ContentPage
{
   public BasePage()
   {
      InitializeComponent();
   }

   protected override void OnAppearing()
   {
      base.OnAppearing();
      (BindingContext as BaseViewModel)?.OnAppearing();
   }
   protected override void OnDisappearing()
   {
      base.OnDisappearing();
      (BindingContext as BaseViewModel)?.OnDisappearing();
   }
}
```

**Comment by LeoHere** [comment] 2016-10-13 10:12
Cool. Thanks. Now I was able to reproduce it. The fact that the ```BasePage``` have an associated ```BasePage.xaml``` file is somehow causing trouble. I mean, if you define ```BasePage``` as a c# class without any associated XAML file you will not have this issue.

I will further investigate and let you know. Thanks both!

**Comment by MarcinDr** [comment] 2016-10-13 10:14
Ye this is exactly what is causing errors in our app. Now we have a 'TestPage' that is not inheriting from our BaseContentPage and this is how we build our views using Gorilla Player :)

**Comment by ShiroYacha** [comment] 2016-10-13 10:31
I have a similar problem with StaticResource but of different cause. In a workaround with Prism, I have to remove the resource dictionary from App.xaml and set the Resource = new MyResource() in code behind in the App(). Since then, the StaticResource does not work but DynamicResource does. Is there a way to fix this?

**Comment by LeoHere** [comment] 2016-10-15 11:28
@ShiroYacha I'm not sure the issue you are describing is the same issue reported here. The issue you are experiencing with Prism is resolved in the dev branch. If the issue is annoying you, send me an email and I can provide you a new installer where it is fixed. Can you please open a new issue providing some sample XAML code illustrating your scenario?

**Comment by airtongomeslima** [comment] 2016-12-04 22:26
I have the same problem, but my application contains only the .cs file, there is no App.xaml file. Maybe this is the problem, the gorilla player do not recognize the app.cs file.

**Comment by LeoHere** [comment] 2016-12-05 10:14
@airtongomeslima, Gorilla does not support styles defined through code, if that is what you are trying to preview.

**Comment by tonholis** [comment] 2017-03-28 16:27
Hi guys!

Same problem here. I just installed Gorilla Player and I'm trying to use in an existing Prism project.
I put some <Color> and <Style> in App.xaml and when I call DynamicResource or StaticResource it doesn't work. It shows the error message: "Can't resolve resources..."

Is there any issues with Prism application?

**Comment by LeoHere** [comment] 2017-03-29 09:02
@tonholis, can you provide more details about your app? i.e. the ```App.xaml``` and the page you are trying to preview. You can trim all the stuff not related to the error if you need to. Also, if you prefer to share it privately, my email in in an earlier comment.

**Comment by nbaua** [comment] 2017-06-05 05:50
I have the same issue too,
Even with the latest version of Gorilla player.

the below is the XAML label in a a test file.

>  < Label Text="Educational Qualification:" StaticResource ProfileSectionHeader}" />

This is the code on app.xaml

![code](https://cloud.githubusercontent.com/assets/17998763/26772043/bf6057fc-49e0-11e7-8f16-2a2fc323bd97.png)

What would be good Idea to resolve this quickly?

![samp problem](https://cloud.githubusercontent.com/assets/17998763/26771979/57031974-49e0-11e7-9907-23660a4df488.png)

**Comment by ormedo** [comment] 2017-07-21 10:51
I´m having the same problem with a Prism application. cant resolve resources

**Comment by LeoHere** [comment] 2017-07-22 11:59
@ormedo did you register prism against the SDK?

Please take a look at [#220](https://github.com/UXDivers/Gorilla-Player-Support/issues/220) which might help you.

This issue is old and should be fixed in v1. I'm closing it. If you still had issues please create a new issue and reference this one.

**Closed by LeoHere** 2017-07-22 11:59 UTC

**Comment by prikazchikof** [comment] 2018-08-03 22:32
What is the end solution for this problem?

**Comment by IoTFier** [comment] 2019-01-07 17:02
Hi @LeoHere , I am experiencing this issue with Prism.DryIoc.Forms v7.1.0431 + XF 3.4.0.1009999 when tried to preview XAML with Gorilla AutoConfig and/or SDK. Any input on how to address this ?

Thanks
