### ISSUE TITLE
Frame CornerRadius not shown in preview

### ISSUE THREAD

**Issue by Mr-Pearce** [UXDivers/Gorilla-Player-Support#218] opened 2017-07-04 07:30 UTC
Using Xamarin.Forms 2.3.4.247
Gorilla 1.0.0.2
On iOS and Android

**Comment by LeoHere** [comment] 2017-07-05 12:06
What player are you using to preview? The one in the store, the gorilla Player solution installed along with Gorilla or the SDK?

**Comment by Mr-Pearce** [comment] 2017-07-05 13:53
The Player is my app using Gorilla SDK

**Comment by EncryptedNomad** [comment] 2017-07-05 15:25
Where can I download 1.0.0.2? All I can seem to find is the 0.9.1.2 and that prompts that it's the latest version

**Comment by nickl-martin** [comment] 2017-07-19 18:15
In the latest Gorilla Player app version it now shows an error when setting the corner radius. Previously I believe it just didn't take the actual value into effect.

`Cannot assign property "CornerRadius": Property does not exists, or is not assignable, or mismatching type between value and property.`

Pretty easy to reproduce. Just make a frame with the corner radius property and view with Gorilla Player app (not using SDK). When using the SDK it works fine for some reason.

Xamarin.Forms 2.3.4.247
Gorilla App (Android) 1.0.0.15

**Comment by LeoHere** [comment] 2017-07-21 10:15
The problem is that both the player in the store and the `Player.sln` installed by Gorilla's installer are using Xamarin Forms 2.3.3.175, and probably `CornerRadius` was introduced in a later version of Forms. In order to fix the issue you just need to update the Xamarin Forms package version used in the `Player.sln` to the latest and deploy it again.

We will update the apps in the store to use the latest version.

**Comment by Im-PJ** [comment] 2017-09-10 10:50
@LeoHere Have you updated the player app in play store? I'm using latest version but still getting this error

**Comment by vijaypalve** [comment] 2017-09-29 05:03
Frame CornerRadius not shown on ios

**Comment by LeoHere** [comment] 2017-10-06 11:56
Hi All. Yesterday we released **Gorilla 1.1.0.4**. The player has been both in the store and the companion solution to **XF 2.4.0.282*. This issue should be fixed. Closing the issue now. If the problem persists open the issue again.

**Closed by LeoHere** 2017-10-06 11:56 UTC
