### ISSUE TITLE
Image Source using Local and  IMarkupExtension doesn't work

### ISSUE THREAD

**Issue by sebastianolafhandjojo** [UXDivers/Gorilla-Player-Support#61] opened 2016-03-19 08:03 UTC
Image Source using Local and IMarkupExtension doesn't work

as shown in this example: 
https://github.com/xamarin/xamarin-forms-samples/blob/master/WorkingWithImages/WorkingWithImages/EmbeddedImageResourceExtension.cs

example XAML usage:

<Image Source="{local:ImageResource SomeFolder.Images.SomeImage.png}"/>

**Comment by LeoHere** [comment] 2016-03-19 13:00
Are you using Gorilla SDK? Can you please give more details on the error you got. Also, please add the example XAML, since it was missing from your previous post.

**Comment by sebastianolafhandjojo** [comment] 2016-03-19 14:29
Hi Leonardo

I attached you the video
I hope u can see it



-olaf-

**Comment by LeoHere** [comment] 2016-03-19 20:10
Can't see any attachment :(

**Comment by sebastianolafhandjojo** [comment] 2016-03-20 03:35
![20-mar-16 11-35-15](https://cloud.githubusercontent.com/assets/10486790/13902721/abc83d52-ee8f-11e5-9059-0001c561148c.png)
![20-mar-16 11-36-01](https://cloud.githubusercontent.com/assets/10486790/13902725/c8b31fcc-ee8f-11e5-9f37-037560dc93d3.png)

**Comment by sebastianolafhandjojo** [comment] 2016-03-20 03:36
<?xml version="1.0" encoding="UTF-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"  	
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
	x:Class="BookingApp.SearchRoomView" 
	xmlns:local="clr-namespace:BookingApp;assembly=BookingApp" 
	xmlns:sys="clr-namespace:System;assembly=mscorlib" 
	Title="Find A Room"
	Style="{StaticResource pageStyle}" >
    <ContentPage.Padding>
        <OnPlatform x:TypeArguments="Thickness">
            <OnPlatform.iOS>0, 20, 0, 0</OnPlatform.iOS>
            <OnPlatform.Android>0, 0, 0, 0</OnPlatform.Android>
            <OnPlatform.WinPhone>0, 0, 0, 0</OnPlatform.WinPhone>
        </OnPlatform>
    </ContentPage.Padding>
     <ContentPage.Resources>
         <ResourceDictionary>
	      
        </ResourceDictionary> 
    </ContentPage.Resources>
    <ContentPage.Content>
        <StackLayout>
            <Grid ColumnSpacing="3" RowSpacing="3">
                <Label Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="3" HeightRequest="10" Text="Enter Your Start Time" HorizontalOptions="FillAndExpand" Style="{StaticResource labelStyle}" HorizontalTextAlignment="Center"/>
                <Entry Grid.Row="1" Grid.Column="0" Grid.ColumnSpan="3" x:Name="StartTime" HorizontalOptions="FillAndExpand" Style="{StaticResource entryStyle}"  Placeholder="..."/>

                <Label Grid.Row="2" Grid.Column="0" Grid.ColumnSpan="2" Text="Duration in Min" Style="{StaticResource labelStyle}"/>
                <Entry Grid.Row="2" Grid.Column="2" HorizontalOptions="FillAndExpand" x:Name="DurationMin" Style="{StaticResource entryStyle}" Placeholder="..."/>

                <Label Grid.Row="3" Grid.Column="0" Grid.ColumnSpan="3" Text="Number Of Person" Style="{StaticResource labelStyle}"/>



<Image HeightRequest="50" WidthRequest="60" Grid.Row="4" Grid.Column="0" x:Name="MinButton" Source="{local:ImageResource BookingApp.Images.minus.png}">
<Image.GestureRecognizers>
    <TapGestureRecognizer Tapped="OnMinTapGestureRecognizerTapped" />
</Image.GestureRecognizers>
</Image>


<Entry  Grid.Row="4" Grid.Column="1" x:Name="PersonCount" HorizontalOptions="FillAndExpand" Text="1" HorizontalTextAlignment="Center" Placeholder="..."/>

<Image HeightRequest="50" WidthRequest="60" Grid.Row="4" Grid.Column="2" x:Name="PlusButton" Source="{local:ImageResource BookingApp.Images.plus.png}">
<Image.GestureRecognizers>
    <TapGestureRecognizer Tapped="OnPlusTapGestureRecognizerTapped" />
</Image.GestureRecognizers>
</Image>


<Image HeightRequest="50" WidthRequest="60" Grid.Row="5" Grid.Column="0" x:Name="ProjectorImage" Source="{local:ImageResource BookingApp.Images.Projector.png}">
<Image.GestureRecognizers>
    <TapGestureRecognizer Tapped="OnProjectorTapGestureRecognizerTapped" />
</Image.GestureRecognizers>
</Image>

<Image HeightRequest="50" WidthRequest="60" Grid.Row="5" Grid.Column="1" x:Name="VoipTelephoneImage" Source="{local:ImageResource BookingApp.Images.Voip.png}">
<Image.GestureRecognizers>
    <TapGestureRecognizer Tapped="OnVoipTapGestureRecognizerTapped" />
</Image.GestureRecognizers>
</Image>



                <Button  Grid.Row="6" Grid.Column="0" Grid.ColumnSpan="3" Text="Search" HorizontalOptions="FillAndExpand" Clicked="OnSearchClick" Style="{StaticResource buttonStyle}" />

            </Grid>
        </StackLayout>
    </ContentPage.Content>

</ContentPage>

**Comment by sebastianolafhandjojo** [comment] 2016-03-20 03:38
[SearchRoom.XAML.txt](https://github.com/UXDivers/Gorilla-Player-Support/files/181161/SearchRoom.XAML.txt)

**Comment by sebastianolafhandjojo** [comment] 2016-03-20 03:39
Hi
Sorry for the trouble.
Answering your question, am not using Gorilla SDK (if you mean in the package in the solution)

**Comment by sebastianolafhandjojo** [comment] 2016-03-20 04:21
![20-mar-16 12-23-55](https://cloud.githubusercontent.com/assets/10486790/13902823/437a5daa-ee96-11e5-9371-b6770d82dd09.png)

**Comment by sebastianolafhandjojo** [comment] 2016-03-20 04:22
Hi Leo 
It should look like the last picture

**Comment by bilalov** [comment] 2016-03-25 17:12
I have this problem. You can reproduction it - just to realization [Xamarin Forms: Embedded Images using Xaml](https://developer.xamarin.com/guides/xamarin-forms/working-with/images/#Embedded_Images)

**Comment by sebastianolafhandjojo** [comment] 2016-04-04 14:47
bilalov, 
The problem is when I Implement the IMarkupExtension, 
I can't see the images in Gorilla Player

**Comment by LeoHere** [comment] 2016-04-05 09:36
@sebastianolafhandjojo Can you try to integrate the SDK in your solution and register the assembly where you implemented the IMarkupExtension as a known assembly? There are still some limitations in the SDK we are working on, but I think that your scenario should work with the SDK from 0.8.3.0.

**Comment by sebastianolafhandjojo** [comment] 2016-04-05 09:42
ok will try




-olaf-

On Tue, Apr 5, 2016 at 5:36 PM, Leonardo Rodríguez <notifications@github.com

**Comment by LeoHere** [comment] 2016-04-05 09:49
Ok, cool. Follow [this](https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK) tutorial to setup the SDK.

**Comment by sebastianolafhandjojo** [comment] 2016-04-05 09:52
Ok will follow that



-olaf-

On Tue, Apr 5, 2016 at 5:49 PM, Leonardo Rodríguez <notifications@github.com

**Comment by sebastianolafhandjojo** [comment] 2016-04-14 10:33
Hi Leonardo

Where is the DLL folder
if i use Mac ?





-olaf-

**Comment by LeoHere** [comment] 2016-04-14 11:12
By default is ~/Gorilla/Lib

**Comment by LeoHere** [comment] 2016-08-01 12:56
I'm closing the issue. If you are still experiencing the issue please open a new isssue and reference this one.

**Closed by LeoHere** 2016-08-01 12:56 UTC
Labels: investigate

**Comment by sebastianolafhandjojo** [comment] 2016-08-01 13:03
Hi
Ok thank you
Sorry forgot to reply to close it





-olaf-

On Mon, Aug 1, 2016 at 8:56 PM, Leonardo Rodríguez <notifications@github.com
