### ISSUE TITLE
Prism support - again

### ISSUE THREAD

**Issue by JamesPetras** [UXDivers/Gorilla-Player-Support#158] opened 2016-09-04 15:25 UTC
Hi guys,

I struggle to make Gorilla player to work with my application. I saw issues #50 and #114 but comments posted there didn't help me.

So I have Gorilla player v0.9.1.2 and and app with Prism 6.2. I've integrated SDK as per instructions but when ever I view a page I a get message: Resorce not found.

As per instructions I've updated Gorilla.json file and it looks like this:

```
{
    "knownAssemblies":[
        { "name": "UXDivers.Artina.Shared" },
        { "name" : "Prism" },
        { "name" : "Prism.Core" },
        { "name" : "Prism.Forms" },
        { "name" : "Prism.Unity.Forms" }
    ]
} 
```

Also In app delegate

```
#if GORILLA
            LoadApplication(UXDivers.Gorilla.iOS.Player.CreateApplication(
                new UXDivers.Gorilla.Config("Good Gorilla").RegisterAssembliesFromTypes<
                UXDivers.Artina.Shared.CircleImage,
                 Prism.IActiveAware,

                       Prism.PrismApplicationBase<App>,
                       Prism.Unity.PrismApplication>()));
#else
```

As you can see I've modified yor line of code

from 
Prism.PrismApplicationBase
to Prism.PrismApplicationBase<App>

as wtihout <> parameter complier was saying:
Using the generic type PrismApplicationBase<T> requires 1 type argument. 

My parameter App was pure guessing, but obviosly it doen't work. If I change in my app.xaml 

prism:PrismApplication to Application Gorilla player works perfectly. 

How can I register my app XML to work?

Thanks

**Comment by LeoHere** [comment] 2016-09-05 12:06
Is there any chance I can get access to the source code? It will be much easier. If it is possible write me to l r o d r i g u e z at u x d i v e r s . c o m.

**Comment by JamesPetras** [comment] 2016-09-05 12:19
Thanks Leo,

I've emailed you the source code

Thank you in advance

**Comment by LeoHere** [comment] 2016-09-06 12:12
I can confirm there is a bug causing this issue. It will be fixed in the next release.

**Comment by ShiroYacha** [comment] 2016-10-03 12:56
Hi, 

I have a similar issue but instead I got into lots of : 

"Cannot read property '__DependsOnResources' of undefined "

I am using the exact Gorilla.json and Config objects. Also, why is that the config name ignored when selecting the server at startup (in the documentation of Gorilla SDK)? I seems to me that the Config object is ignored.

Thanks in advance

**Comment by khadeeja-alif** [comment] 2018-11-22 14:02
Is there some issue with running Gorilla SDK with Prism Dryioc?. Can't seem to access resources in App.xaml file in my prism application with gorilla sdk

**Comment by LeoHere** [comment] 2018-11-22 14:10
@khadeeja-alif are you getting any specific error? Can you please include the Grial SDK configuration?

**Comment by khadeeja-alif** [comment] 2018-11-22 14:15
I get StaticResource not found, even after registering prism assembly.  I am using UXDivers.GorillaPlayer.SDK 1.5.0

               LoadApplication(UXDivers.Gorilla.Droid.Player.CreateApplication(
            this,
            new UXDivers.Gorilla.Config("Good Gorilla")
              //FFImageLoading.Forms
              .RegisterAssemblyFromType<FFImageLoading.Forms.CachedImage>()
              //FFImageLoading Svg
               .RegisterAssemblyFromType<SvgCachedImage>()
               //SfListView
                .RegisterAssemblyFromType<SfListView>()
                //SfTabView
                .RegisterAssemblyFromType<SfTabView>()
                //Prism
                .RegisterAssemblyFromType<Prism.IActiveAware>()
                .RegisterAssemblyFromType<PrismApplicationBase>()
                .RegisterAssemblyFromType<Prism.DryIoc.PrismApplication>()
                //Application PCL
                .RegisterAssembly(typeof(App).Assembly)
            ));

**Comment by LeoHere** [comment] 2018-11-22 22:35
@khadeeja-alif for Prism application I would recommend that you use the `UseApplication(new App(), this, new Config()...)` method instead of the `CreateApplication`. The create application creates a new Xamarin Forms standard application. Prism applications require the App to be a PrismApplication.

Still this does not explains the `StaticResource` not found issue. Can you provide a little more detail about the resource not being found? The best would be to have a tiny solution where I can reproduce the problem. If that is not possible please paste the relevant parts of the XAML.

**Comment by khadeeja-alif** [comment] 2018-11-23 07:19
This is my App.xaml file. 

<?xml version="1.0" encoding="utf-8"?>
<prism:PrismApplication xmlns="http://xamarin.com/schemas/2014/forms" 
                        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
                        xmlns:prism="clr-namespace:Prism.DryIoc;assembly=Prism.DryIoc.Forms" 
                        x:Class="MyProject.App">
    <Application.Resources>
        
        <ResourceDictionary>
            <OnPlatform x:TypeArguments="x:String" x:Key="BoldFont">
                 <On Platform="Android" Value="Exo-SemiBold.ttf#Exo SemiBold" />
                 <On Platform="iOS" Value="Exo-SemiBold" />
            </OnPlatform>
             <OnPlatform x:TypeArguments="x:String" x:Key="RegularFont">
                   <On Platform="Android" Value="Exo-Regular.ttf#Exo Regular" />
                   <On Platform="iOS" Value="Exo-Regular" />
            </OnPlatform>
            <Style TargetType="Label">
                <Setter Property="FontFamily" Value="{StaticResource RegularFont}"/>
            </Style>
            <Style TargetType="Entry">
                <Setter Property="FontFamily" Value="{StaticResource RegularFont}"/>
            </Style>
            <Style TargetType="Button">
                <Setter Property="FontFamily" Value="{StaticResource RegularFont}"/>
            </Style>
             <Style TargetType="Editor">
                <Setter Property="FontFamily" Value="{StaticResource RegularFont}"/>
            </Style>
            <Style TargetType="View">
                <Setter Property="BackgroundColor" Value="White"/>
            </Style>
            
            <Style TargetType="ContentPage">
                 <Setter Property="BackgroundColor" Value="White"/>
            </Style>
            
            
            <Color x:Key="AppPurpleColor">#704191</Color>
            <Color x:Key="PrimaryTextColor">#323232</Color>
            <Color x:Key="SecondaryTextColor">#BEBEBE</Color>
            <Color x:Key="AppOrangeColor">#F0916E</Color>
            <Color x:Key="AppGreenColor">#32BEA6</Color>
            
            </ResourceDictionary>
    </Application.Resources>
</prism:PrismApplication>

This is a Basic View I created

<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             x:Class="MyProject.TestPage">
    <ContentPage.Content>
        <Frame>
           <Label Text="Welcome to Xamarin Forms"
                  HorizontalTextAlignment="Center"
                  VerticalTextAlignment="Center"/> 
        </Frame>
    </ContentPage.Content>
</ContentPage>

![img_0883](https://user-images.githubusercontent.com/14857549/48931726-e2070100-ef1d-11e8-8b1d-4e64ddbc338c.PNG)

It shows up fine.

Once I call the style from my code

<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             x:Class="MyProject.TestPage">
    <ContentPage.Content>
        <Frame>
           <Label Text="Welcome to Xamarin Forms"
                  HorizontalTextAlignment="Center"
                  VerticalTextAlignment="Center"
                  FontFamily="{StaticResource RegularFont}"/> 
        </Frame>
    </ContentPage.Content>
</ContentPage>

![img_0885](https://user-images.githubusercontent.com/14857549/48931757-0236c000-ef1e-11e8-8991-4c281f4bd57e.PNG)

It gives me this error.

Same goes for the colors.

<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             x:Class="MyProject.TestPage">
    <ContentPage.Content>
        <Frame>
           <Label Text="Welcome to Xamarin Forms"
                  HorizontalTextAlignment="Center"
                  VerticalTextAlignment="Center"
                  TextColor="{StaticResource AppOrangeColor}"/> 
        </Frame>
    </ContentPage.Content>
</ContentPage>

![img_0884](https://user-images.githubusercontent.com/14857549/48931796-2abeba00-ef1e-11e8-98db-3bd3af9737ce.PNG)

It gives me the same error.

**Comment by khadeeja-alif** [comment] 2018-11-23 07:43
Okay. Thanks.!

Got the StaticResource issue solved. T'was a minor mistake in my App.xaml file.

**Comment by LeoHere** [comment] 2018-11-27 13:04
Closing the issue since it is a pretty old issue. Please open a new issue if the problem persists.

**Closed by LeoHere** 2018-11-27 13:04 UTC

**Comment by IoTFier** [comment] 2019-01-07 04:06
Hi @LeoHere , how are you? Happy New Year !

Using Gorilla SDK I have completed many of my UIs ; in I have also used some 3rd party controls e.g. Syncfusion control library.

Now I am trying to copy my XAML Pages, resources, theme in a new Prism v7.1 + XF 3.4 based project which is configured to use the UXDivers.GorillaPlayer.SDK.AutoConfig which is in the beta version.

I added known assemblies in Gorilla.json  by specifying 
"knownAssemblies": [
    { "name": "Prism" },
    { "name": "Prism.Forms" },
    { "name": "Prism.Unity.Forms" }
  ]

I don't see any Gorilla server page when I ran the App as per instruction at https://github.com/UXDivers/Gorilla-Player-Support/wiki/Release-Notes-Gorilla-Player-1.5 
What am I missing here  ?

Then I tried to use Gorilla player deployed on iOS simulator to preview my changes. But, even then Gorilla is not able to resolve Root XAML element 
![image](https://user-images.githubusercontent.com/26844611/50748409-f3227d80-11fe-11e9-9be2-151735971a3e.png)

Will you please help me in resolving this issue ?
I would appreciate it. 

Thanks
